### ISSUE TITLE
When exporting to PDF, quote breaks that page and any following pages

### ISSUE THREAD

**Issue by RicoTrevisan** [bennyxguo/Obsidian-Obsidianite#26] opened 2021-02-10 14:53 UTC
Lovely theme, thanks for it.

A quote ">" on a page breaks the PDF page and then any following pages.

[Obsidianite PDF test.pdf](https://github.com/TriDiamond/Obsidian-Obsidianite/files/5958912/Obsidianite.PDF.test.pdf)

Steps to reproduce it:
1. create a document
1. add lots of text in it - so that it expands over multiple pages when exported as a PDF
1. add a quote ">" somewhere in the text.
2. in which ever page that quote appears, all the text of that page will be gibberish.
3. all following pages will be gibberish, too.

(Just in case: I tried a couple of different formats - A5, A5 Landscape, Letter, Letter Landscape - it happens there, too.)

**Comment by TriDiamond** [comment] 2021-03-27 15:59
I will have to specially work on PDF export, a lot of the styles I do doesn't support PDF export. This is marked will be worked on on next versions.

**Comment by krokofant** [comment] 2022-10-09 16:30
I cannot reproduce this.

**Comment by bennyxguo** [comment] 2022-10-09 23:25
> I cannot reproduce this.

I guess we can close this for now?

**Comment by krokofant** [comment] 2022-10-09 23:46
> I guess we can close this for now?

Yes, it seems like it. It might've been fixed in Obsidian itself. I found a few closed issues regarding garbled pdf export.

**Closed** 2022-10-09 23:47 UTC
Labels: bug, enhancement
